version: "3"
services:
  loan-management-api:
    build:
      context: ../loan-management-api
      dockerfile: Dockerfile
    image: loan-management-api
    container_name: loan-management-api
    restart: unless-stopped
    tty: true
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      AUTH_API_PORT: ${AUTH_API_PORT}
      DATABASE_URL: ${DATABASE_URL}
      PAYMENT_CONCEPT_ID: ${PAYMENT_CONCEPT_ID}
      LATE_FEE_CONCEPT_ID: ${LATE_FEE_CONCEPT_ID}
    ports:
      - '3000:3000'
    expose:
      - 3000
    links:
      - loan-management-ui
    networks:
      - code-network
  loan-management-ui:
    build:
      context: ../loan-management-ui
      dockerfile: Dockerfile
    image: loan-management-ui
    container_name: loan-management-ui
    volumes:
      - ../loan-management-ui/dist:/app/dist
  web:
    image: nginx:latest
    container_name: loan-management-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../loan-management-ui/dist:/var/www/html:ro
      - ./web-config/000-default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - loan-management-ui
    networks:
      - code-network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  code-network:
    driver: bridge
